# Generated by Django 5.2.1 on 2025-06-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
